dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.13 MATPLOTLIB=2.2.4 CASADI=3.1.0 NOSE=1.3.7

notifications:
  email: false

install:
 - sudo apt install libgfortran3 python-tk
 - pip install --yes numpy=$NUMPY scipy=$SCIPY matplotlib=$MATPLOTLIB nose=$NOSE casadi=$CASADI
 - python setup.py install

before_script:

# Fake display for testing the plotting features
# http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - nosetests --exe -v

