dist: bionic
language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 CASADI=3.1.0 NOSE=1.3.7 MOCK=2.0.0

notifications:
  email: false

install:
 - sudo apt update && sudo apt install libgfortran3 
 - pip install numpy==$NUMPY casadi==$CASADI nose==$NOSE mock==$MOCK
 - python setup.py install

script:
 - nosetests --exe -v

